[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node server/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments]
  [environments.production]
  NODE_ENV = "production"
  PORT = "8080"
  # JWT_SECRET is automatically set via Railway
  # DATABASE_URL is automatically set when the PostgreSQL plugin is added

  [environments.preview]
  NODE_ENV = "production"
  PORT = "8080"